apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus_uid
    jsonData:
      httpMethod: GET

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki_uid
    jsonData:
      maxLines: 1000

  - name: Postgres Exporter
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: postgres_exporter_uid
    jsonData:
      httpMethod: GET
    metricFindQuery: |
      label_values(pg_up)
