monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: group
            members: [streamed, loki]
        streamed:
            type: stream
            path: 'php://stdout'
            level: debug
        loki:
            type: service
            id: App\Service\LokiLoggerService
            level: debug
