# This file is the entry point to configure your own services.
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\VaultService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Factory\LoggerFactory:
        arguments:
            $vaultService: '@App\Service\VaultService'

    Psr\Log\LoggerInterface:
        factory: ['@App\Factory\LoggerFactory', 'createLogger']

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
