parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\VaultService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Factory\LogServiceFactory:
        arguments:
            $vaultService: '@App\Service\VaultService'

    App\Factory\AIServiceFactory:
        arguments:
            $vaultService: '@App\Service\VaultService'
            $logger: '@Psr\Log\LoggerInterface'

    App\Factory\GraphDBServiceFactory:
        arguments:
            $vaultService: '@App\Service\VaultService'
            $logger: '@Psr\Log\LoggerInterface'

    Psr\Log\LoggerInterface:
        factory: ['@App\Factory\LogServiceFactory', 'create']

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
