# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python_demo'
    metrics_path: /metrics
    static_configs:
      - targets: ['python_demo:5020']

  - job_name: 'postgres'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8088']