# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pdf_processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['pdf_processor:5020']

  - job_name: 'postgres'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres_exporter:9187']