pg_stat_activity_successful:
  query: "SELECT time_bucket('1 hour', time) AS bucket, COUNT(*) AS successful_requests FROM api_logs WHERE status = '200' GROUP BY bucket"
  metrics:
    - bucket:
        usage: "LABEL"
        description: "Time bucket in hours"
    - successful_requests:
        usage: "COUNTER"
        description: "Number of successful OpenAI API requests"

pg_stat_activity_failed:
  query: "SELECT time_bucket('1 hour', time) AS bucket, COUNT(*) AS failed_requests FROM api_logs WHERE status != '200' GROUP BY bucket"
  metrics:
    - bucket:
        usage: "LABEL"
        description: "Time bucket in hours"
    - failed_requests:
        usage: "COUNTER"
        description: "Number of failed OpenAI API requests"
